# Generated by Django 3.2 on 2023-02-22 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название меню')),
            ],
            options={
                'verbose_name': 'Основное меню',
                'verbose_name_plural': 'Основные меню',
            },
        ),
        migrations.CreateModel(
            name='SecondMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название меню')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.mainmenu')),
            ],
            options={
                'verbose_name': 'Меню второго уровня',
                'verbose_name_plural': 'Меню второго уровня',
            },
        ),
        migrations.CreateModel(
            name='LastMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название меню')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.secondmenu')),
            ],
            options={
                'verbose_name': 'Последнее меню',
                'verbose_name_plural': 'Последние меню',
            },
        ),
    ]
