# Generated by Django 3.2 on 2023-02-22 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmenu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_menu', to='menu.secondmenu'),
        ),
        migrations.AlterField(
            model_name='lastmenu',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='secondmenu',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_menu', to='menu.mainmenu'),
        ),
        migrations.AlterField(
            model_name='secondmenu',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
